### ISSUE TITLE
Downloads page: Marketo form 

### ISSUE THREAD

**Issue by varshavaradarajan** [gocd/www.go.cd#1078]
Required fields (*) misaligned

<img width="1124" alt="Screen Shot 2019-10-21 at 11 40 13 AM" src="https://user-images.githubusercontent.com/4715748/67233997-1d91a000-f3f9-11e9-9940-c69159a66412.png">

**Comment by veerababukona** [comment]
It's happening due to ad blockers in the Mozilla browser or else the alignment is working fine.
We tested with chrome, Mozilla, and Safari.

**Comment by chadlwilson** [comment]
This has been removed subsequent to this.
