### ISSUE TITLE
Add a way for people to subscribe for updates when downloading

### ISSUE THREAD

**Issue by kmugrage** [gocd/www.go.cd#154]
We don't have any way to push important notifications to people who have downloaded Go in the past. At the same time, we don't want to require people to give any personal information in order to download.

We should add a mechanism where people can opt-in to other Go related information easily. One idea which came up in an offline conversation was a basic pop-up for people to enter an email address after they click download.

**Comment by arvindsv** [comment]
Closing this. This is from old site. Also, there is now a "Subscribe to updates" button. I think it should be moved, but that's a different conversation.
