### ISSUE TITLE
Investigate if go.cd is kramdown/jekyll v3 compliant

### ISSUE THREAD

**Issue by ketan** [gocd/www.go.cd#245]
https://github.com/blog/2100-github-pages-now-faster-and-simpler-with-jekyll-3-0

Textile/RedCloth has been officially declared dead for GH pages as of 1st May.

**Comment by zabil** [comment]
We'll be moving the site to middleman with erb and compiled pages before that.

**Comment by ketan** [comment]
Where do I see the work in progress?

**Comment by zabil** [comment]
Setting it up to be shared today. Expect to see it in a bit.

**Comment by arvindsv** [comment]
Took a look. Current site is not fully compatible. Some formatting breaks. For example, [this page](https://www.go.cd/2015/12/28/gocd-continuous-delivery-through-pipelines.html). Unfortunate, because I wanted some of the settings from kramdown (especially parse_block_html).

**Comment by ketan** [comment]
Closing since we've moved to a new site
