### ISSUE TITLE
Jitter when hovering on "join our community images"

### ISSUE THREAD

**Issue by ketan** [gocd/www.go.cd#284]
When you hover over the images, there's a slight delay while the browser loads the hover version of the image. Any way to preload that?

/cc @naveenbhaskar, let me know if you need help with this.

**Comment by markandan** [comment]
@ketan: Its been changed to Font-Awesome and now its loading properly there's no delay in loading the image. We cab close this issue.

**Comment by ketan** [comment]
Thank you @markandan
