### ISSUE TITLE
Create a "Security" section

### ISSUE THREAD

**Issue by zabil** [gocd/www.go.cd#286]
- Publish details on https://go.cd about how to report a vulnerability (e.g. via support.thoughtworks.com).
- Publish a GPG public key on https://go.cd with the above info so that people can encrypt their communication with the team

Here is what a few other projects are doing
- http://rubyonrails.org/security/
- https://www.ruby-lang.org/en/security/
- http://www.apache.org/security/

**Comment by markandan** [comment]
@zabil : we added a section under contribute page. Please have a look and close the issue
