### ISSUE TITLE
Downloads page do not show up experimental builds

### ISSUE THREAD

**Issue by rajiesh** [gocd/www.go.cd#288]
go.cd download page provides links for experimental builds too below the stable builds list(in the previous version of go.cd site) but currently we do not have that option on downloads page. Constructed the URL for a experimental release builds from the stable release URL, but it returned 'Access Denied' erro - URL tried: https://download.go.cd/binaries/16.5.0-3228/win/go-server-16.5.0-3228-setup.exe

**Comment by ketan** [comment]
@rajiesh — that's intentional. For now use https://www.go.cd/download/?experimental=true

**Comment by ketan** [comment]
also you forgot the `/experimental/` prefix in the download URL

**Comment by rajiesh** [comment]
Thanks @ketan I did try experimental prefix but like this `binaries/experimental/version`, looks like it should be this  - https://download.go.cd/experimental/binaries/16.5.0-3228/win/go-server-16.5.0-3228-setup.exe. Closing this issue
