### ISSUE TITLE
Unable to download GoCD Server and Agent

### ISSUE THREAD

**Issue by kakimanitrinath** [gocd/www.go.cd#311]
![Uploading Error.jpg…]()

**Comment by zabil** [comment]
@kakimanitrinath 

We don't see the image that you've tried to attach here.

**Comment by kakimanitrinath** [comment]
![error](https://cloud.githubusercontent.com/assets/17175560/16984414/6c8331e8-4e97-11e6-985b-3aa2ca4ed635.jpg)

**Comment by zabil** [comment]
This is likely to happen if you can't access this url, can you try clicking on the link below?

https://download.go.cd/releases.json

Also, are you behind a firewall?

**Comment by zabil** [comment]
@kakimanitrinath is it working for you now?

**Comment by kakimanitrinath** [comment]
Nope :( still not working and latest link which you have provided is not able to browse.

**Comment by kakimanitrinath** [comment]
I downloaded and installed thanks
