### ISSUE TITLE
Add section on page for reporting security issues

### ISSUE THREAD

**Issue by zabil** [gocd/www.go.cd#314]
We have a page on hackerone for reporting security defects.
http://hackerone.com/gocd

We need to set up a link on our [contribute](https://www.go.cd/contribute/) page describing where to report security defects.

**Comment by markandan** [comment]
@zabil: we've added a section in contribute page. Please look into the same and close the issue

**Comment by markandan** [comment]
@zabil : this is the duplicate of #286. We can close the same
