### ISSUE TITLE
SCM plugins are broken/copypasted

### ISSUE THREAD

**Issue by tedder** [gocd/www.go.cd#321]
Hi, on the SCM plugins file(`data/scm_plugins.yml`), all of the plugins have the same URLs and mostly the same data. The authors and project names vary, but the rest of it is the same. I don't think one plugin should be listed four times. I can't find a version in history that is different.

https://github.com/gocd/www.go.cd/blob/master/data/scm_plugins.yml

**Comment by ketan** [comment]
Hi,

This is intentional, some of those repositories actually build multiple related/similar plugins :)

https://github.com/gocd-contrib/gocd-build-status-notifier/releases
https://github.com/gocd-contrib/gocd-oauth-login/releases
