### ISSUE TITLE
Show all issues on https://www.go.cd/releases when linking to comprehensive list

### ISSUE THREAD

**Issue by Byron-TW** [gocd/www.go.cd#327]
The status quo: [releases][pr-only] (shows PRs only).
My suggestion: [releases][all-issues] (shows PRs and issues).

I believe people interested in the details should also see issues, which may very well we [critical bugfixes][json-api-breakage].

If this request gets accepted, I would be happy to fix the current release links in a PR.

[pr-only]: https://github.com/gocd/gocd/pulls?q=is%3Apr+milestone%3A%22Release+16.8%22+is%3Amerged
[all-issues]: https://github.com/gocd/gocd/issues?utf8=%E2%9C%93&q=milestone%3A%22Release%2016.8%22
[json-api-breakage]: https://github.com/gocd/gocd/issues/2529

**Comment by ketan** [comment]
Sounds reasonable, please submit a PR.
