### ISSUE TITLE
"On Failure" only step

### ISSUE THREAD

**Issue by Stono** [gocd/www.go.cd#380]
Hi, 
It'd be nice to have an explicit "on failure" step.
To give some context, we use Kubernetes and deploy our pods using kubernetes Deployments.  In GoCD we wait until the deployment has completed, or time out, in either case if it doesn't work we can explicitly rollback to the previous deployment with "kubectl rollout undo deployment/name".

It'd be nice to have this command run automatically, if the previous command failed :-)

At the moment we can achieve it with a manual trigger step, but that requires human intervention.

Karl

**Comment by zabil** [comment]
@Stono can you raise this issue at https://github.com/gocd/gocd/issues instead?
