### ISSUE TITLE
[Download page] List down all the available revisions

### ISSUE THREAD

**Issue by ermauliks** [gocd/www.go.cd#57]
Currently we've to select revisions from drop-down, moreover, drop-down is useless because as an user I don't know what was baked in that build. Better we do something like this?

* tabular view with auto-selected OS based on which OS I'm on,
* sort revisions by time,
* highlight GA/verified builds with check-mark or something,
* show time and links to Go Dashboard/VSM.

![download-page](https://cloud.githubusercontent.com/assets/3040988/3764647/c976a9e6-18b3-11e4-9fba-4cf815404bc5.png)

(for demonstrate all the above points, I've created this mock)

**Comment by arvindsv** [comment]
Closing this. This is from old site.
