### ISSUE TITLE
Allow users to go from VSM to config, make changes, and then navigate back to the VSM.

### ISSUE THREAD

**Issue by naveenbhaskar** [gocd/www.go.cd#626]
My Initial thoughts are given below. 

**OPTION 1**

1. we can put a gear icon in the pipeline, user clicks on it and lands on the config page.
![image](https://user-images.githubusercontent.com/1627961/28615101-92f01272-7215-11e7-9918-37ca97bea251.png)

2. User make changes, go back to vsm by clicking "back to vsm"  link
back to vsm link is conditional. It will appear only when a user visit config page from a VSM

![image](https://user-images.githubusercontent.com/1627961/28615811-031afcf4-7218-11e7-82a4-7fd5a41a0bae.png)

another option with a different placement of back to vsm link

![image](https://user-images.githubusercontent.com/1627961/28615835-19c7f1c8-7218-11e7-89a4-73fc131749e2.png)

**OPTION 2**
Config  has to open in an overlay in the same VSM page. user make the config changes and save it and close the overlay. 
But this has lot of blockers, 
1. we have two config edits now, which one should we add, 
2. Config edit needs lot of space , hence cant just include in an overlay with the current design.
3. if we decides to go with this option, then need to redesign config page
![image](https://user-images.githubusercontent.com/1627961/28616172-61851f76-7219-11e7-895e-dffbf6ec47fe.png)

**Comment by arvindsv** [comment]
I'm not sure the "Back to VSM" makes sense. There is not one VSM for a config. If you move across pages, I don't know what that should like to.

**Comment by naveenbhaskar** [comment]
forgot to mention that back to vsm is conditional. it will show up only when a user is visiting config from a vsm. 
(i will add this point in the fpost)

**Comment by arvindsv** [comment]
Even with that, when using the old config edit, it's across multiple pages. So, that link would go away.

**Comment by streisguth** [comment]
Is there a reason why a user would need to go directly from a Run's VSM to a Pipeline Configuration page? To me, the interaction is more meaningful to navigate to the configuration for a Pipeline in the context of a Pipeline (ie navigating to the config through either the Pipeline Group or Pipeline Activity pages). This eliminates the association of a Pipeline's Configuration with a particular Run.

**Comment by eeluke** [comment]
Steven and I are talking about this one right now - we think that this feature would make more sense as part of a map or "workflow" of pipelines rather than the VSM simply because the VSM is not static and is associated with a run (as Steven mentioned). @arvindsv Can you give us an example of a convincing case for this feature on the VSM view?

**Comment by naveenbhaskar** [comment]
Lot of users have asked for a link to config from vsm. so having a link make sense. but coming back from config to vsm doesn't make sense. So the scope of story is just to give an option to navigate to config from VSM and adding a gear icon solves the issue.

i have talked to duck yesterday regarding this and he suggested the same.

**Comment by maheshp** [comment]
I have not felt a need for this, but this might be useful for users to quickly find the dependent pipelines and make the changes (especially in absence of configuration `workflow` view).

Given the negligible effort to add this, I think it should be ok to experiment by adding it.

**Comment by jyotisingh** [comment]
I think adding a link to pipeline-config from vsm would be useful. I have found a need for it just to view the config, esp the pipeline dependencies since the current VSM doesn't provide the upstream stage name.

What I am unclear about is the "back to vsm" button. So far we don't really have a back-to-anything button anywhere. So, are you suggesting we do the following?
* when a user navigates to the pipeline-config from dashboard, the button should read "back to dashboard"
* navigate to config from job details page, then "back to job details"
* navigate to config from stage details page, then "back to stage details"
* navigate from vsm, then "back to vsm"
or something along those lines?

To me the "back to <anything>" button seems to give the same thing as a browser back. I am the worst when it comes to talking about UX, but is an explicit "back" button supposed to be better than a browser back?

**Comment by arvindsv** [comment]
We decided that the back to VSM doesn't work - since there are multiple VSMs and other complications such as moving across pages in the config. So, this is only about going from VSM to config.

**Comment by jyotisingh** [comment]
ah cool, that makes sense to me. I would find it useful.

**Comment by streisguth** [comment]
I have mockups for a VSM navigation story, that includes some additions to the header for improved wayfinding. The design team has seen this already, and I plan to make a github issue for it today. It will likely have a positive impact on this story and other UX improvements related to navigation.

**Comment by eeluke** [comment]
Yes, headers will improve wayfinding. But, context switching (between
pages) is already hard for users and if we don't give them a way back (or,
rather, a way to their next logical step), we fail them and make their
workflow more tedious.

So, would the workflow for using this "link to config" go something like
this:

I'm in the VSM and I can see all the dependencies for a specific run of a
specific pipeline - I notice that a stage is failing in an upstream
dependency and I have a suspicion why it's failing - I want to go to the
config for that pipeline and change something. Then I want to rerun the
pipeline. Then I want to check the VSM for that run to see that it is green
now.

Or, if that's not a scenario, can someone please walk me through the flow
in it's entirety?

Thanks,
Emily

Emily Luke
Head of User Experience,
ThoughtWorks Studios <http://www.thoughtworks.com/products>
Email eluke@thoughtworks.com
Telephone +1 908 209 6204 <+1+908+209+6204>
[image: ThoughtWorks]
<http://www.thoughtworks.com/?utm_campaign=emily-luke-signature&utm_medium=email&utm_source=thoughtworks-email-signature-generator>

**Comment by naveenbhaskar** [comment]
so lets put the config button in the pipeline and close the story, since Back to VSM doesn't make sense as per developers. Any more updates on this ?

**Comment by eeluke** [comment]
I would like clarification on my email above. Is that the scenario? Or
would the flow be different?

Emily Luke
Head of User Experience,
ThoughtWorks Studios <http://www.thoughtworks.com/products>
Email eluke@thoughtworks.com
Telephone +1 908 209 6204 <+1+908+209+6204>
[image: ThoughtWorks]
<http://www.thoughtworks.com/?utm_campaign=emily-luke-signature&utm_medium=email&utm_source=thoughtworks-email-signature-generator>

**Comment by eeluke** [comment]
Thanks, @arvindsv . I get it. The "seeing the effect of that change" is what I want to make sure we think about. So, maybe it doesn't make sense to go back to the VSM, but we should think about what _does_ make sense after you change the config. If it's too complex, we can break that out into another story. I just don't want to leave the user hanging after they make the change.

**Comment by varshavaradarajan** [comment]
Closing this as @maheshp has introduced this in 17.9. https://github.com/gocd/gocd/pull/3734
