### ISSUE TITLE
Windows download page blank

### ISSUE THREAD

**Issue by kmugrage** [gocd/www.go.cd#74]
After #73 was merged, the file list is blank when I first visit it.

If I click on a different OS and then click back it works

Chrome Version 37.0.2062.103 m
Windows 7

![2014-09-07 22_27_20-download](https://cloud.githubusercontent.com/assets/3209933/4181429/0767d10c-3719-11e4-8607-1f35035e48cd.png)

**Comment by arvindsv** [comment]
Closing this. This is from old site.
