### ISSUE TITLE
release notes for 18.2

### ISSUE THREAD

**Issue by ketan** [gocd/www.go.cd#750]

**Comment by varshavaradarajan** [comment]
- [ ] Known issues section for Quicker Dashboard. 
      - [ ]  Trigger with options inconsistency
- [ ] Point to feature toggle docs to turn quicker dashboard off. 
- [ ] Plugin Status report 
- [ ] Deprecate EA v1 and v2

**Comment by varshavaradarajan** [comment]
- [ ] Move users API to Breaking changes section. Its been removed by https://github.com/gocd/gocd/commit/703bf06481535aa2d583e12c461361e25cb52749 
- [ ] Deprecation notice for Notification endpoint v1

**Comment by ketan** [comment]
> Deprecation notice for Notification endpoint v1

Discussed with @maheshp — Makes no sense to say v1 is deprecated, and ask plugin authors to move to v2. And next deprecate v2 and have plugin authors move to v3. We will deprecate v1 and v2 when v3 is released and ask authors to migrate from v1 to v3 directly.
