### ISSUE TITLE
The "Personalize" dropdown is hard to use when there are lots of pipelines.

### ISSUE THREAD

**Issue by phedinkus** [gocd/www.go.cd#765]
When there are a lot of pipelines the dropdown becomes very hard to use. It would be nice if it were searchable and larger or even on a new page so one could easily configure their dashboard view.

**Comment by arvindsv** [comment]
@phedinkus Thanks! https://github.com/gocd/gocd/issues/3842 might be a better place for this, since this is the repo for the GoCD website. Do you mind taking a look at the discussion in the linked issue and commenting, please?

Thank you! I'll close this issue here.

**Comment by phedinkus** [comment]
Yes!! Thank you.
