### ISSUE TITLE
[Download page] Issues with Linux

### ISSUE THREAD

**Issue by arikagoyal** [gocd/www.go.cd#81]
1) On firefox 24, on centos, this is what i see. Though all appears disabled, i can click on any OS , and from that point things start working fine

![download_page_firefox](https://cloud.githubusercontent.com/assets/6175869/4214819/d060334c-38c7-11e4-9cd7-a87d6a844bf0.png)

2) Default OS highlighting when the download page is opened on a browser on Linux, does not work correctly. Currently by default it always takes you to debian installers even if you are on a centos box

**Comment by arvindsv** [comment]
Closing this. This is from old site.
